### ISSUE TITLE
implement hand rolled auth

### ISSUE THREAD

**Issue by meatwallace** [meatwallace/campaign#26]
reference epic-stack's implementation for a best practice implementation. good way to refresh myself on a best practice implementation.

- [x] sign up - email (#45)
- [x] log in - email (#45)
- [x] verification (#45)
- [x] totp (#45)
- [x] bot honeypot (#45)
- [x] forgot password -> password reset (#40, #46)
- [x] onboarding (priv policy/T&Cs) (#45)
